id: I3F5292FA
legacy_id: P001699
ocr_import_info:
  bdrc_scan_id: W1CZ878
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T08:11:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:37:47.895743+00:00'
last_modified: 2022-08-31 03:38:30.167583
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ878
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ878
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངོར་ཆོས་འབྱུང་།
  author: ངོར་མཁན་ཆེན ༢༥་སངས་རྒྱས་ཕུན་ཚོགས།
statistics:
  ocr_word_mean_confidence_index: 0.4598424717452178
  ocr_word_median_confidence_index: 0.36000001430511475
quality: null
bases:
  I1CZ2115:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2115
      total_pages: 464
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2115.txt
    statistics:
      ocr_word_median_confidence_index: 0.36000001430511475
      ocr_word_mean_confidence_index: 0.4598424717452178
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
