id: P001699
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ878
  title: ངོར་ཆོས་འབྱུང་།
  author: ''
  volumes:
    da5f678b4b52450fb2b818f09da457aa:
      image_group_id: I1CZ2115
      title: ''
      volume_number: 1
      total_pages: 464
      base_file: v001.txt
