id: P001699
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ878
  title: ངོར་ཆོས་འབྱུང་།
  author: ''
  volumes:
    da5f678b4b52450fb2b818f09da457aa:
      image_group_id: I1CZ2115
      title: ''
      volume_number: 1
      total_pages: 464
      base_file: v001.txt
